#! /bin/sh

### BEGIN INIT INFO
# Provides:          ruby-web3
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the ruby web3 server
# Description:       starts ruby web3 using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#DAEMON=/root/cloud/web/server/start-bash-web3
NAME=ruby-web3
DESC=ruby-web3

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet -m \
		--pidfile /var/run/$NAME.pid  \
		--exec /usr/bin/ruby /root/cloud/web/server/web3.rb \
		> /root/cloud/web/server/web3.out 2> /root/cloud/web/server/web3.err &
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet \
		--pidfile /var/run/$NAME.pid  \
		--exec /usr/bin/ruby /root/cloud/web/server/web3.rb \
		> /root/cloud/web/server/web3.out 2> /root/cloud/web/server/web3.err &
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet \
		--pidfile /var/run/$NAME.pid  \
		--exec /usr/bin/ruby /root/cloud/web/server/web3.rb \
		> /root/cloud/web/server/web3.out 2> /root/cloud/web/server/web3.err &
	sleep 1
	start-stop-daemon --start --quiet -m \
		--pidfile /var/run/$NAME.pid  \
		--exec /usr/bin/ruby /root/cloud/web/server/web3.rb \
		> /root/cloud/web/server/web3.out 2> /root/cloud/web/server/web3.err &
	echo "$NAME."
	;;
  status)
	status_of_proc -p /var/run/$NAME.pid "$DAEMON" ruby-web3 && exit 0 || exit $?
	;;
  *)
	echo "Usage: $NAME {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0
